name: Execute Script

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      new_docker_version:
        description: 'Provide a new docker version.'     
        required: true
        default: 'master.a1c905b.7290957852'
      base_docker_version:
        description: 'Provide an existing version.'     
        required: false
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_GH_TOKEN }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "GITHUB_WORKSPACE, ${{ github.workspace }}"
          ls

      - name: Make the script files executable
        run: chmod +x ./.github/scripts/docker_version_replacer.sh

      - name: Run the scripts
        run: |
          ./.github/scripts/docker_version_replacer.sh "dev" "acrapplications.azurecr.io" "common" "eventflowwebapi" "${{ github.event.inputs.new_docker_version }}" "${{ github.event.inputs.base_docker_version }}"

          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "chore(deps): update $new_docker_version"
          git push

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "DOCKERVERSION_REPLACER<<$EOF" >> $GITHUB_ENV
          cat dockerversion_replacer_out.md >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPO_GH_TOKEN }}
          script: |
            const output = `#### Validate Docker Versions 🖌
            <details><summary>Show Validate</summary>\n
            \`\`\`\n
            ${process.env.DOCKERVERSION_REPLACER}
            \`\`\`
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.rest.issues.createComment({
              issue_number: 40,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
