name: Execute Script

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      new_docker_version:
        description: 'Provide a new docker version.'     
        required: true
        default: 'master.a1c905b.7290957852'
      base_docker_version:
        description: 'Provide an existing version.'     
        required: false
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_GH_TOKEN }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "GITHUB_WORKSPACE, ${{ github.workspace }}"
          ls

      - name: Make the script files executable
        run: chmod +x ./.github/scripts/docker_version_replacer.sh

      - name: Run the scripts
        run: |
          ./.github/scripts/docker_version_replacer.sh "dev" "acrapplications.azurecr.io" "common" "eventflowwebapi" "${{ github.event.inputs.new_docker_version }}" "${{ github.event.inputs.base_docker_version }}"

          cat dockerversion_replacer_out.md

